### PR TITLE
correctly detect http://localhost (and maybe port)

### LINKED ISSUE #1: http://localhost:3000 should be a valid url
```
    #[test]
    fn localhost() {
        assert!(is_url("http://localhost"));
    }

    #[test]
    fn localhost_with_port() {
        assert!(is_url("http://localhost:3000"));
    }
```

### PR DESCRIPTION
**Pull request by root-talis**
Closes #1.

### CODE REVIEW

**Comment by mauro-balades** [comment]
Looks good. Does it detect `http://hello` as an URL too?

**Comment by root-talis** [comment]
> Looks good. Does it detect `http://hello` as an URL too?

Yep :)

**Comment by mauro-balades** [comment]
should it be detected though? I don't think it should.

**Comment by root-talis** [comment]
Section 3.2.2 of [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) states that:
```
   host        = IP-literal / IPv4address / reg-name
```

Followed by:

```
   A registered name intended for lookup in the DNS uses the syntax
   defined in Section 3.5 of [RFC1034] and Section 2.1 of [RFC1123].
   Such a name consists of a sequence of domain labels separated by ".",
   each domain label starting and ending with an alphanumeric character
   and possibly also containing "-" characters.
```

Section 3.5 of [RFC 1034](https://datatracker.ietf.org/doc/html/rfc1034) states:

```
The following syntax will result in fewer problems with many
applications that use domain names (e.g., mail, TELNET).

<domain> ::= <subdomain> | " "

<subdomain> ::= <label> | <subdomain> "." <label>

<label> ::= <letter> [ [ <ldh-str> ] <let-dig> ]

<ldh-str> ::= <let-dig-hyp> | <let-dig-hyp> <ldh-str>

<let-dig-hyp> ::= <let-dig> | "-"

<let-dig> ::= <letter> | <digit>

<letter> ::= any one of the 52 alphabetic characters A through Z in
upper case and a through z in lower case

<digit> ::= any one of the ten digits 0 through 9
```

Which means that a domain is either a " " or a subdomain, where a subdomain is:
 1) either a  label, or
 2) another subdomain, followed by a ".", followed by a  label.

Further definition of label does not contain a ".".

Therefore, I suppose a domain name in a URL **may consist of any single label**, which consists of letters, digits, hyphens, and without any dots.

---

Mostly irrelevant, but still:

Section 2.1 of [RFC 1123](https://datatracker.ietf.org/doc/html/rfc1123#page-13) states:

```
      One aspect of host name syntax is hereby changed: the
      restriction on the first character is relaxed to allow either a
      letter or a digit.  Host software MUST support this more liberal
      syntax.
```

**Comment by mauro-balades** [comment]
looks good 👍🏽

**Pull request merged**
